import { Box, Container, Divider, styled, Typography } from '@mui/material';
import React from 'react';

function TermsAndConditions() {

    const FirstPage = () => {
        return (
            <MainBox>
                <Container maxWidth="md" sx={{ mt: 4, mb: 4 }}>
                    <Box sx={{ p: 3, display: 'flex', flexDirection: 'column', gap: 2 }}>

                        <Typography variant="h4" component="h1" gutterBottom align="center" fontWeight="bold">
                            Z-Mart | Terms And Conditions
                        </Typography>

                        <Divider sx={{ mb: 2 }} />

                        <Typography variant="body1" color="text.secondary" align="justify">
                            This document is an electronic record in accordance with the Information Technology Act, 2000
                            and the relevant rules. It is generated by a computer system and does not require any physical
                            or digital signatures.
                        </Typography>

                        <Typography variant="body1" color="text.secondary" align="justify">
                            This document is published pursuant to Rule 3 (1) of the Information Technology (Intermediaries
                            Guidelines) Rules, 2011, which mandates the publication of the rules and regulations, privacy
                            policy, and terms of use for access or usage of the{' '}
                            <a href="https://www.localhot:3000.com" style={{ color: '#1976d2', textDecoration: 'none' }}>
                                www.megamartfashions.com
                            </a>{' '}
                            website.
                        </Typography>

                        <Typography variant="body1" color="text.secondary" align="justify">
                            The domain name{' '}
                            <a href="https://www.localhost:3000.com" style={{ color: '#1976d2', textDecoration: 'none' }}>
                                www.megamartfashions.com
                            </a>{' '}
                            (hereinafter referred to as the "Website") is owned by Megamart Lifestyle Brands Limited, a
                            company incorporated under the Companies Act, 1956, with its registered office located at Naroda
                            Road, Railwaypura Post, Ahmedabad, and its corporate office at 8th Floor, Du Parc Trinity Building,
                            17 M.G. Road, Bangalore 560 001 (hereinafter referred to as "Megamart").
                        </Typography>

                        <Typography variant="body1" color="text.secondary" align="justify">
                            Your use of the Website, its services, and tools is governed by the following terms and conditions
                            ("Terms of Use"), including applicable policies incorporated herein by reference. By using the
                            Website, you agree to comply with these Terms of Use. If you transact on the Website, you will be
                            subject to the policies applicable to such transactions. By mere use of the Website, you shall be
                            contracting with Megamart, and these terms and conditions, including the applicable policies,
                            constitute your binding obligations with Megamart.
                        </Typography>

                        <Typography variant="body1" color="text.secondary" align="justify">
                            For these Terms of Use, "You" or "User" shall mean any natural or legal person who agrees to become
                            a buyer on the Website by providing registration data while registering as a registered user. Megamart
                            does not allow purchases without registration. The terms "We", "Us", or "Our" refer to Megamart.
                        </Typography>

                        <Typography variant="body1" color="text.secondary" align="justify">
                            When you use any of the services provided by us through the Website, including but not limited to
                            product reviews or seller reviews, you will be subject to the rules, guidelines, policies, and
                            terms and conditions applicable to such services, which are considered part of these Terms of Use.
                            We reserve the right, at our sole discretion, to change, modify, add, or remove portions of these
                            Terms of Use at any time without prior notice. It is your responsibility to review these Terms of
                            Use periodically for updates or changes. Continued use of the Website following any changes
                            constitutes your acceptance.
                        </Typography>

                    </Box>
                </Container>
            </MainBox>
        )
    }


    return (
        <>{FirstPage()}</>
    )
}

export default TermsAndConditions;

const MainBox = styled(Box)({})